"""
Django settings for clendar_backend project.

Generated by 'django-admin startproject' using Django 3.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'nm^^#=8+)k4$v7dhq*!j6lmn_0#ok3x*qn4u(cejj@dtwqk#jp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

appsPath = os.path.join(BASE_DIR, 'apps')
extra_appPath = os.path.join(BASE_DIR, 'extra_app')
if appsPath not in sys.path:
    sys.path.insert(0, appsPath)
    sys.path.insert(0, extra_appPath)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'constance',

    'app_user',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'clendar_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'clendar_backend.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'clendar_backend',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'"
        },
    },
}

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/
LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# 小程序
WX_APPID = 'wx8e27af581b67dcaa'
WX_APPSECRET = '8c241c987756f6ec6db75f1af6b8260a'
# 小程序配置
WEAPP_CONFIGS = {
    'wx8e27af581b67dcaa': {
        'app_secret': '8c241c987756f6ec6db75f1af6b8260a'
    },
    'wxee1270eb80fa4fef': {
        'app_secret': '3a0d5c811164710b180b3d7e8e728175'
    },

}

import redis

pool = redis.BlockingConnectionPool(host='localhost', port=6379, db=1, max_connections=1000, socket_timeout=60 * 60)
REDIS_CLIENT = redis.StrictRedis(connection_pool=pool)

import logging

log_format = "[%(levelname)1.1s %(asctime)s] [%(filename)s:%(lineno)d] [%(funcName)s] %(message)s"
logging.basicConfig(format=log_format, level=logging.DEBUG)

# django constance config
CONSTANCE_REDIS_CONNECTION = 'redis://localhost:6379/0'
CONSTANCE_ADDITIONAL_FIELDS = {  # example fields
    'yes_no_null_select': ['django.forms.fields.ChoiceField', {
        'widget': 'django.forms.Select',
        'choices': ((None, "-----"), ("yes", "Yes"), ("no", "No"))
    }],
    'image_field': ['django.forms.ImageField', {}],
}

CONSTANCE_CONFIG = {
    'be_agent_need_phone': (True, '注册代理是否要求手机号', bool),
    'be_agent_by_self': (True, '是否可以自助成为代理', bool),
    'upgrade_role_2_member_count': (10, '升级经理团长，绑定下级买家数', int),
    'upgrade_role_3_member_count': (100, '升级总监团长，有效直属经理团长数', int),
    'upgrade_role_3_team_count': (300, '升级总监团长，有效团队团长数', int),
    'upgrade_role_3_rebate_amount': (2000, '升级总监团长，当月直属经理团长贡献的佣金', int),
    'withdrawal_service_charge_rate': (0, '提现手续费百分比', int),
    'withdraw_date': ("23,24", '可提现日期'),
    'goods_detail_banner_ad': (True, '开启详情页广告', bool),
    'wx_withdraw': (True, '开启微信提现', bool),
    'zfb_withdraw': (True, '开启支付宝提现', bool),
    'official_pid': (21978290, '官方账号', int),
    'min_withdrawal_amount': (10, '最低提现金额，单位元', int)
}

CONSTANCE_CONFIG_FIELDSETS = {
    '代理升级': (
        'be_agent_need_phone',
        'be_agent_by_self',
        'upgrade_role_2_member_count',
        'upgrade_role_3_member_count',
        'upgrade_role_3_team_count',
        'upgrade_role_3_rebate_amount',
    ),
    '其它选项': (
        'withdrawal_service_charge_rate',
        'withdraw_date',
        'goods_detail_banner_ad',
        'wx_withdraw',
        'zfb_withdraw',
        'official_pid',
        'min_withdrawal_amount',
    ),
}

from .local_settings import *
