# Generated by Django 3.0.1 on 2019-12-28 07:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unionid',
                 models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='微信unionid')),
                ('avatar_url', models.CharField(blank=True, max_length=512, verbose_name='微信头像url')),
                ('nickname', models.CharField(blank=True, max_length=256, verbose_name='微信昵称')),
                ('wechat_id', models.CharField(blank=True, max_length=256, null=True, verbose_name='微信号')),
                ('token', models.CharField(max_length=32, unique=True, verbose_name='token')),
                ('openid',
                 models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='微信openid(小程序)')),
                ('session_key',
                 models.CharField(blank=True, max_length=256, null=True, verbose_name='session_key(小程序)')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='姓名')),
                ('password', models.CharField(blank=True, max_length=64, null=True, verbose_name='登录密码')),
                ('temporary_invite_pid', models.IntegerField(blank=True, null=True, verbose_name='临时代理PID')),
                ('gender', models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='性别')),
                ('country', models.CharField(blank=True, max_length=256, null=True, verbose_name='所在国家')),
                ('province', models.CharField(blank=True, max_length=256, null=True, verbose_name='所在省份')),
                ('city', models.CharField(blank=True, max_length=256, null=True, verbose_name='所在城市')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('last_login_time', models.DateTimeField(blank=True, null=True, verbose_name='上次登录时间')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
    ]
