# Generated by Django 2.1.2 on 2019-12-29 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_grading', models.CharField(max_length=32, verbose_name='时间粒度')),
                ('login_time', models.DateTimeField(verbose_name='登录时间')),
                ('user',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_user.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户登录',
                'verbose_name_plural': '用户登录',
            },
        ),
    ]
